// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PingProvider is an autogenerated mock type for the PingProvider type
type PingProvider struct {
	mock.Mock
}

// Ping provides a mock function with given fields: element
func (_m *PingProvider) Ping(element string) error {
	ret := _m.Called(element)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(element)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPingProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewPingProvider creates a new instance of PingProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPingProvider(t mockConstructorTestingTNewPingProvider) *PingProvider {
	mock := &PingProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
